# Generated by Django 2.1.4 on 2019-02-26 07:06

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-create_time']},
        ),
        migrations.AlterField(
            model_name='blog',
            name='contene',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
